[toolchain]

[workspace]
members = ["programs/*"]

[features]
seeds = false
skip-lint = false

[programs.localnet]
game = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
booty = "BootyTokenProgram11111111111111111111111111"

[programs.devnet]
game = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
booty = "BootyTokenProgram11111111111111111111111111"

[programs.mainnet]
game = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
booty = "BootyTokenProgram11111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
